[package]
name = "sqrl"
version = "0.1.0"

[dependencies]
aes-gcm = "0.10.1"
base64 = "0.21.0"
byteorder = "1.4.3"
ed25519-dalek = "1.0.1"
hmac = "0.12.1"
num-bigint = "0.4"
num-traits = "0.2.15"
rand = "0.8"
scrypt = "0.11.0"
sha2 = "0.10.6"
url = "2.3"
x25519-dalek = { version = "2.0.0", features = ["static_secrets"] }
