[package]
name = "sqrl"
version = "0.1.0"

[dependencies]
aes-gcm = "0.10"
base64 = "0.21"
byteorder = "1"
ed25519-dalek = "2"
hmac = "0.12.1"
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"
scrypt = "0.11"
sha2 = "0.10"
url = "2"
x25519-dalek = { version = "2", features = ["static_secrets"] }
