[package]
name = "sqrl"
version = "0.1.0"

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.21.7"
byteorder = "1.5.0"
ed25519-dalek = "2.1.1"
hmac = "0.12.1"
num-bigint = "0.4.4"
num-traits = "0.2.18"
rand = "0.8.5"
scrypt = "0.11.0"
sha2 = "0.10.8"
url = "2.5.0"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
